### ISSUE TITLE
Color is setting the wrong color profile.

### ISSUE THREAD

**Issue by prince-ugwuh-volusion** [jwaitzel/SuggestedColors#3]
I'm seeing an issue where when I select a color from the list. It sets the color but its darker. When I found out the reason from http://stackoverflow.com/questions/14578759/wrong-color-in-interface-builder. I notice it is continuously setting the wrong color profile when it should be on generic rgb. When I set the color manually its fine. I like the tool can you look into this issue?

**Comment by dral3x** [comment]
+ 1

**Comment by jwaitzel** [comment]
Let me know if it's fixed now. I change NSColor to CalibratedColor... but not sure.

**Comment by dral3x** [comment]
It works! Thank you @jwaitzel !
