### ISSUE TITLE
Warning on building app (both in XCode and AppCode)

### ISSUE THREAD

**Issue by dral3x** [jwaitzel/SuggestedColors#5]
When I build my app (with SuggestedColors installed on my machine) I read this warning.

```
Error:objc[5339]: Class XCBuildConfiguration is implemented in both /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore and /Users/alex/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SuggestedColors.xcplugin/Contents/MacOS/SuggestedColors. One of the two will be used. Which one is undefined.
```

Do you have an idea of why this is happening and how to fix it?
Thanks

**Comment by jwaitzel** [comment]
hmm, I know what XCBuildConfiguration is, but not sure why is giving you problems.
XCBuildConfiguration is a class inside the XCodeEditor framework which I use to add the suggested color file in the xcode project file ( ***.xcodeproj).
Seems that my plugin and that plugins are conflicting, let me check it.

**Comment by jwaitzel** [comment]
Ok I renamed the XCBuildConfiguration class to XCBuildConfig.
Should be fixed, let me know so I can close this.
