### ISSUE TITLE
SuggestedColors not working with Xcode 6.3.2

### ISSUE THREAD

**Issue by Prince2k3** [jwaitzel/SuggestedColors#6]
I updated Alcatraz and noticing that I can't use the plugin.

**Comment by SimplGy** [comment]
Also no-go here. xcode 6.3.2 Doesn't show up in the edit menu, installed with Alcatraz.

**Comment by mcmurrym** [comment]
I see this log in the system console after a fresh install: 5/26/15 10:49:46.719 AM Xcode[76419]: Suggested colors file not found...

**Comment by jwaitzel** [comment]
Yeah, I have to update the plugin UUID which changes with every xcode update

**Comment by jwaitzel** [comment]
Should be fixed, let me know so I can close this.
